// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          int         `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
}

type User struct {
	ID         int            `db:"id" json:"id"`
	Name       string         `db:"name" json:"name"`
	LastName   string         `db:"last_name" json:"last_name"`
	Email      string         `db:"email" json:"email"`
	Cellphone  pgtype.Text    `db:"cellphone" json:"cellphone"`
	BaseSalary pgtype.Numeric `db:"base_salary" json:"base_salary"`
}

type UserFinance struct {
	ID              int              `db:"id" json:"id"`
	UserID          int64            `db:"user_id" json:"user_id"`
	Amount          pgtype.Numeric   `db:"amount" json:"amount"`
	TransactionType int64            `db:"transaction_type" json:"transaction_type"`
	CategoryID      int64            `db:"category_id" json:"category_id"`
	TransactionDate pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
}
