services:
  db:
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${SYNCDAY_DATABASE_USER}
      POSTGRES_DB: ${SYNCDAY_DATABASE_NAME}
      POSTGRES_PASSWORD: ${SYNCDAY_DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local